### ISSUE TITLE
Unable to perform ssh-copy-id

### ISSUE THREAD

**Issue by phanikumar1210** [junegunn/ssh-copy-id.rb#1]
I am trying to implement ssh-copy-id with ssh-copy-id.rb with the following command
ssh-copy-id.rb   remote_hostname -i ~/.ssh/id_dsa.pub -u remote_username -p remote_password remote_username:remote_password@remote_hostname:22 

It even prompting me for the password. Could you please help me out in resolving this

**Comment by junegunn** [comment]
`gem update ssh-copy-id.rb` and see if it helps. There's not much I can do if it still doesn't work. The project hasn't been maintained for years, and I don't recommend using it. Sorry!
